# Get the image and the corresponding label. Compare them qform

In [120]:
import nrrd as nr
import nibabel as nib
import os
import numpy as np

In [121]:
PATH_sct_large = "../sct-testing-large/"
PATH_label = "deleener_data/"

def get_sct_path(file):
    return f"{PATH_sct_large}{file}/anat/{file}_T2w.nii.gz"

In [122]:
#Correspondence between reference and label data based on `spinal_segments_prediction - data - phase 1.csv'.
#unf
Center1 = {
    "sct_004": "01",
    "sct_005": "02",
    "sct_006": "03",
    "sct_007": "04",
    "sct_008": "05",
    "sct_009": "06",
    "sct_011": "07",
    "sct_012": "08",
    "sct_013": "09",
    "sct_014": "10",
    "sct_015": "11",
    "sct_016": "12",
    "sct_017": "13",
    "sct_018": "14",
    "sct_019": "15",
    "sct_022": "16",
    "sct_024": "17"}
#paris
Center2 = {
    "05": "01",
    "15": "02",
    "16": "03",
    "39": "04",
    "41": "05",
    "42": "06",
    "45": "07",
    "47": "08",
    "61": "09",
    "62": "10",
    "63": "11",
    "66": "12",
    "67": "13",
    "68": "14",
    "69": "15",
    "80": "16",
    "82": "17",
    "83": "18",
    "84": "19",
    "87": "20",
    "112": "21",
    "115": "22",
    "116": "23",
    "117": "24",
}

In [123]:
def get_header(file):
    """
    Return header and qform matrix the file
    Accept .nii.gz and .nrrd extention
    """
    ext = os.path.splitext(file)[1]
    if ext == ".nrrd":
        header = nr.read_header(file)
        matrix = header["space directions"]
    elif ext == ".gz":
        header = nib.load(file).header
        x = header["srow_x"]
        y = header["srow_y"]
        z = header["srow_z"]
        matrix = np.vstack((x, y, z))
    else:
        raise Exception(f"File extention of {file} not supported")
    return header, matrix


In [126]:
## Center1 unf
for sub in Center1:
    reference = sub.split("_")[1]
    label = Center1[sub]
    try:
        nii_header, nii_matrix = get_header(get_sct_path(f"sub-unfSCT{reference}"), True)
        nrrd_header, nrrd_matrix = get_header(f"{PATH_label}center1_Cadotte/{label}_t2-label.nrrd", True)
        print(f"Ref:sub-unfSCT{reference}")
        print(nii_matrix)
        print(f"Label:{label}_t2-label.nrrd")
        print(nrrd_matrix)
    except FileNotFoundError as f:
        print(f"Error on file {f}")
    print("######")

Ref:sub-unfSCT004
[[-6.0117296e-03 -2.5833905e-02  7.9956019e-01 -1.3209519e+01]
 [-7.7918077e-01  1.8132104e-01  0.0000000e+00  8.9816589e+01]
 [ 1.8122135e-01  7.7875239e-01  2.6524169e-02 -2.7307306e+02]]
Label:01_t2-label.nrrd
[[ 8.00000012e-01  3.63901229e-08  4.17830259e-09]
 [ 3.63901236e-08 -7.79180780e-01 -1.81321073e-01]
 [ 4.17830267e-09 -1.81321073e-01  7.79180780e-01]]
######
Ref:sub-unfSCT005
[[-6.0117296e-03 -2.5833905e-02  7.9956019e-01 -1.3209519e+01]
 [-7.7918077e-01  1.8132104e-01  0.0000000e+00  8.1141891e+01]
 [ 1.8122135e-01  7.7875239e-01  2.6524169e-02 -1.8343454e+02]]
Label:02_t2-label.nrrd
[[ 7.99560218e-01 -1.10685630e-07 -2.65231477e-02]
 [-6.01161379e-03 -7.79180784e-01 -1.81221370e-01]
 [ 2.58328818e-02 -1.81321052e-01  7.78752436e-01]]
######
Ref:sub-unfSCT006
[[ 0.0000000e+00  0.0000000e+00  8.0000001e-01 -2.2294432e+01]
 [-7.9842138e-01  5.0232418e-02  0.0000000e+00  1.3428831e+02]
 [ 5.0232418e-02  7.9842138e-01  0.0000000e+00 -2.7055518e+02]]
Label:03